import type { Assessment } from '../types';

export const mockAssessments: Assessment[] = [
  {
    id: 'ast-9001',
    workerId: 'w-101',
    workerName: 'Rajesh Kumar Mahato',
    employeeId: 'JHK-CZ-8842',
    moduleId: 'm-gas',
    moduleName: 'Gas Leak & Confined Space',
    scenarioName: 'Gas Leak & Confined Space Assessment',
    score: 94,
    correctActions: 7,
    wrongActions: 0,
    criticalErrors: 0,
    passFail: 'Pass',
    duration: '04m 12s',
    dateTime: '2026-09-08 14:32:10',
    stepDetails: [
      { stepIndex: 1, stepName: 'Gas Leak Scenario', expectedAction: 'Detect gas leak scenario via AR Surface Detection', performedAction: 'AR surface aligned and gas leak scenario detected', result: 'pass', scoreDelta: 15, timestamp: '00:15' },
      { stepIndex: 2, stepName: 'Hazard Recognition', expectedAction: 'Identify atmospheric hazard in workplace', performedAction: 'Hazard identified correctly', result: 'pass', scoreDelta: 15, timestamp: '00:45' },
      { stepIndex: 3, stepName: 'Hazard Zone Recognition', expectedAction: 'Demarcate hazard zone boundary', performedAction: 'Hazard zone boundary recognized', result: 'pass', scoreDelta: 15, timestamp: '01:20' },
      { stepIndex: 4, stepName: 'PPE Selection', expectedAction: 'Select required respiratory & body PPE', performedAction: 'Correct PPE selected from menu', result: 'pass', scoreDelta: 20, timestamp: '02:05' },
      { stepIndex: 5, stepName: 'Buddy System', expectedAction: 'Confirm buddy system communication protocol', performedAction: 'Buddy system handshake verified', result: 'pass', scoreDelta: 15, timestamp: '03:10' },
      { stepIndex: 6, stepName: 'Confined Space Entry', expectedAction: 'Execute safe response & confined space entry', performedAction: 'Safe response executed according to protocol', result: 'pass', scoreDelta: 14, timestamp: '04:00' },
    ]
  },
  {
    id: 'ast-9002',
    workerId: 'w-102',
    workerName: 'Amit Singh Munda',
    employeeId: 'JHK-CZ-4190',
    moduleId: 'm-gas',
    moduleName: 'Gas Leak & Confined Space',
    scenarioName: 'Gas Leak & Confined Space Assessment',
    score: 92,
    correctActions: 6,
    wrongActions: 1,
    criticalErrors: 1,
    criticalErrorDetails: 'Omitted mandatory PPE Selection in Hazard Zone prior to Confined Space entry (Critical Safety Error - Failed Assessment despite 92% score)',
    passFail: 'Fail',
    duration: '05m 18s',
    dateTime: '2026-09-11 11:14:02',
    stepDetails: [
      { stepIndex: 1, stepName: 'Gas Leak Scenario', expectedAction: 'Identify gas leak scenario', performedAction: 'Scenario initialized', result: 'pass', scoreDelta: 20, timestamp: '00:20' },
      { stepIndex: 2, stepName: 'Hazard Recognition', expectedAction: 'Identify gas hazard location', performedAction: 'Hazard recognized', result: 'pass', scoreDelta: 20, timestamp: '01:10' },
      { stepIndex: 3, stepName: 'Hazard Zone Recognition', expectedAction: 'Demarcate hazard zone', performedAction: 'Zone demarcated', result: 'pass', scoreDelta: 20, timestamp: '02:05' },
      { stepIndex: 4, stepName: 'PPE Selection', expectedAction: 'Select mandated PPE before hazard zone entry', performedAction: 'Bypassed PPE Selection and entered zone', result: 'critical_error', scoreDelta: -30, timestamp: '03:00' },
      { stepIndex: 5, stepName: 'Buddy System', expectedAction: 'Verify buddy system presence', performedAction: 'Buddy verified', result: 'pass', scoreDelta: 16, timestamp: '04:10' },
      { stepIndex: 6, stepName: 'Safe Response', expectedAction: 'Execute safe response procedure', performedAction: 'Response executed', result: 'pass', scoreDelta: 16, timestamp: '05:00' },
    ]
  },
  {
    id: 'ast-9003',
    workerId: 'w-103',
    workerName: 'Sunita Hembrom',
    employeeId: 'JHK-SE-6211',
    moduleId: 'm-mach',
    moduleName: 'Machinery',
    scenarioName: 'Machinery Assessment',
    score: 98,
    correctActions: 5,
    wrongActions: 0,
    criticalErrors: 0,
    passFail: 'Pass',
    duration: '03m 50s',
    dateTime: '2026-08-25 09:40:55',
    stepDetails: [
      { stepIndex: 1, stepName: 'Machinery Operational Readiness', expectedAction: 'Perform pre-op inspection', performedAction: 'Readiness check complete', result: 'pass', scoreDelta: 30, timestamp: '00:45' },
      { stepIndex: 2, stepName: 'Interactions & Guard Safety', expectedAction: 'Verify machine guard positions & interlocks', performedAction: 'Interlocks verified', result: 'pass', scoreDelta: 35, timestamp: '02:00' },
      { stepIndex: 3, stepName: 'Hazard Detection & Emergency Response', expectedAction: 'Respond to simulated emergency stop trigger', performedAction: 'Emergency stop engaged immediately', result: 'pass', scoreDelta: 33, timestamp: '03:40' },
    ]
  },
  {
    id: 'ast-9004',
    workerId: 'w-107',
    workerName: 'Manoj Kumar Gupta',
    employeeId: 'JHK-CZ-5534',
    moduleId: 'm-fire',
    moduleName: 'Fire & Explosion Response',
    scenarioName: 'Fire & Explosion Response Assessment',
    score: 54,
    correctActions: 3,
    wrongActions: 4,
    criticalErrors: 2,
    criticalErrorDetails: 'Selected wrong extinguisher type for active fire; failed to follow evacuation sequence',
    passFail: 'Fail',
    duration: '05m 10s',
    dateTime: '2026-09-13 16:05:40',
    stepDetails: [
      { stepIndex: 1, stepName: 'AR Surface Detection', expectedAction: 'Detect workspace surface via AR', performedAction: 'Surface detected', result: 'pass', scoreDelta: 15, timestamp: '00:25' },
      { stepIndex: 2, stepName: 'Industrial Fire Scenario', expectedAction: 'Initialize fire scenario', performedAction: 'Scenario loaded', result: 'pass', scoreDelta: 15, timestamp: '01:00' },
      { stepIndex: 3, stepName: 'Identify Hazard', expectedAction: 'Identify fire source hazard', performedAction: 'Failed to identify secondary fire source', result: 'fail', scoreDelta: -10, timestamp: '01:45' },
      { stepIndex: 4, stepName: 'Select Extinguisher', expectedAction: 'Select correct extinguisher for fire class', performedAction: 'Selected incorrect extinguisher type', result: 'critical_error', scoreDelta: -25, timestamp: '02:40' },
      { stepIndex: 5, stepName: 'Evacuation Sequence', expectedAction: 'Follow emergency evacuation path to exit', performedAction: 'Re-entered hazard zone during evacuation', result: 'critical_error', scoreDelta: -20, timestamp: '04:30' },
    ]
  },
  {
    id: 'ast-9005',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-SE-3088',
    moduleId: 'm-fire',
    moduleName: 'Fire & Explosion Response',
    scenarioName: 'Fire & Explosion Response Assessment',
    score: 88,
    correctActions: 6,
    wrongActions: 1,
    criticalErrors: 0,
    passFail: 'Pass',
    duration: '04m 05s',
    dateTime: '2026-09-10 10:15:00',
    stepDetails: [
      { stepIndex: 1, stepName: 'AR Surface Detection', expectedAction: 'Scan area for AR surface tracking', performedAction: 'Surface tracking active', result: 'pass', scoreDelta: 15, timestamp: '00:30' },
      { stepIndex: 2, stepName: 'Identify Exit', expectedAction: 'Locate primary evacuation route', performedAction: 'Exit located', result: 'pass', scoreDelta: 20, timestamp: '01:15' },
      { stepIndex: 3, stepName: 'Select Extinguisher', expectedAction: 'Select appropriate extinguisher', performedAction: 'Correct extinguisher chosen', result: 'pass', scoreDelta: 25, timestamp: '02:00' },
      { stepIndex: 4, stepName: 'Use Extinguisher', expectedAction: 'Apply PASS technique to extinguish fire', performedAction: 'Fire extinguished successfully', result: 'pass', scoreDelta: 28, timestamp: '03:40' },
    ]
  }
];
