import type { Assessment } from '../types';

export const mockAssessments: Assessment[] = [
  {
    id: 'ast-9001',
    workerId: 'w-101',
    workerName: 'Rajesh Kumar Mahato',
    employeeId: 'JHK-BS-8842',
    moduleId: 'm-gas',
    moduleName: 'Gas Safety',
    scenarioName: 'Blast Furnace Gas Leak Isolation (CO & N2)',
    score: 92,
    correctActions: 8,
    wrongActions: 1,
    criticalErrors: 0,
    passFail: 'Pass',
    duration: '04m 12s',
    dateTime: '2026-09-08 14:32:10',
    stepDetails: [
      { stepIndex: 1, stepName: 'Area Hazard Inspection', expectedAction: 'Activate handheld CO detector before entry', performedAction: 'Handheld CO detector switched on & zeroed', result: 'pass', scoreDelta: 15, timestamp: '00:15' },
      { stepIndex: 2, stepName: 'PPE Check', expectedAction: 'Don SCBA positive pressure mask', performedAction: 'SCBA donned, seal test verified', result: 'pass', scoreDelta: 15, timestamp: '00:45' },
      { stepIndex: 3, stepName: 'Valve Identification', expectedAction: 'Locate Bleeder Valve #4 BFG Line', performedAction: 'Located Valve #4 BFG Line', result: 'pass', scoreDelta: 10, timestamp: '01:20' },
      { stepIndex: 4, stepName: 'Isolation Lock (LOTO)', expectedAction: 'Apply padlock and warning tag to Bleeder #4', performedAction: 'Padlock attached, safety tag affixed', result: 'pass', scoreDelta: 20, timestamp: '02:05' },
      { stepIndex: 5, stepName: 'Line Pressure Purge', expectedAction: 'Purge remaining gas with Nitrogen injection', performedAction: 'Delayed Nitrogen purge by 20 sec', result: 'fail', scoreDelta: -8, timestamp: '03:10' },
      { stepIndex: 6, stepName: 'Control Room Escalation', expectedAction: 'Radio control room supervisor with pressure clearance', performedAction: 'Radio alert transmitted with clear sensor log', result: 'pass', scoreDelta: 20, timestamp: '04:00' },
    ]
  },
  {
    id: 'ast-9002',
    workerId: 'w-102',
    workerName: 'Amit Singh Munda',
    employeeId: 'JHK-DC-4190',
    moduleId: 'm-gas',
    moduleName: 'Gas Safety',
    scenarioName: 'Methane (CH4) Sensor Calibration & SCBA Evacuation',
    score: 68,
    correctActions: 4,
    wrongActions: 3,
    criticalErrors: 1,
    criticalErrorDetails: 'Failed to verify SCBA tank pressure gauge before entering methane accumulation zone (>2.5% CH4)',
    passFail: 'Fail',
    duration: '06m 45s',
    dateTime: '2026-09-11 11:14:02',
    stepDetails: [
      { stepIndex: 1, stepName: 'Atmospheric Pre-check', expectedAction: 'Inspect continuous methanometer telemetry', performedAction: 'Checked telemetric sensor display', result: 'pass', scoreDelta: 15, timestamp: '00:20' },
      { stepIndex: 2, stepName: 'SCBA Pressure Verification', expectedAction: 'Check SCBA cylinder pressure >250 bar', performedAction: 'Omitted pressure verification (entered at 110 bar)', result: 'critical_error', scoreDelta: -30, timestamp: '01:10' },
      { stepIndex: 3, stepName: 'Sensor Calibration', expectedAction: 'Span calibration with 2.5% CH4 test gas', performedAction: 'Inaccurate span calibration potentiometer setting', result: 'fail', scoreDelta: -10, timestamp: '03:40' },
      { stepIndex: 4, stepName: 'Emergency Evacuation Signal', expectedAction: 'Trigger underground evacuation alarm bell', performedAction: 'Activated alarm within 15 seconds', result: 'pass', scoreDelta: 20, timestamp: '05:15' },
    ]
  },
  {
    id: 'ast-9003',
    workerId: 'w-103',
    workerName: 'Sunita Hembrom',
    employeeId: 'JHK-JM-6211',
    moduleId: 'm-mach',
    moduleName: 'Machinery Safety',
    scenarioName: 'Overhead Gantry Crane Interlock & Emergency Stop',
    score: 100,
    correctActions: 9,
    wrongActions: 0,
    criticalErrors: 0,
    passFail: 'Pass',
    duration: '03m 50s',
    dateTime: '2026-08-25 09:40:55',
    stepDetails: [
      { stepIndex: 1, stepName: 'Pre-operational Interlock Verification', expectedAction: 'Verify limit switches on crane bridge travel', performedAction: 'Tested all 4 limit switches successfully', result: 'pass', scoreDelta: 25, timestamp: '00:30' },
      { stepIndex: 2, stepName: 'Load Hook Latch Lock', expectedAction: 'Inspect safety latch on 50T hook assembly', performedAction: 'Safety latch inspected and locked', result: 'pass', scoreDelta: 25, timestamp: '01:30' },
      { stepIndex: 3, stepName: 'Emergency Stop Drill', expectedAction: 'Simulate power surge and trip E-stop button', performedAction: 'E-stop engaged in 0.8 seconds', result: 'pass', scoreDelta: 25, timestamp: '02:45' },
      { stepIndex: 4, stepName: 'Tagout Sign-off', expectedAction: 'Log crane operational status in digital logbook', performedAction: 'Logbook entry created with digital signature', result: 'pass', scoreDelta: 25, timestamp: '03:40' },
    ]
  },
  {
    id: 'ast-9004',
    workerId: 'w-107',
    workerName: 'Manoj Kumar Gupta',
    employeeId: 'JHK-DC-5534',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety',
    scenarioName: 'Heavy Dumper Engine Compartment Fire Extinction',
    score: 54,
    correctActions: 3,
    wrongActions: 4,
    criticalErrors: 2,
    criticalErrorDetails: 'Opened engine hood directly during active Class B fire without standing upwind; failed to pull safety pin on AFFF extinguisher',
    passFail: 'Fail',
    duration: '05m 10s',
    dateTime: '2026-09-13 16:05:40',
    stepDetails: [
      { stepIndex: 1, stepName: 'Fire Discovery & Vehicle Stop', expectedAction: 'Engage park brake & turn off master ignition switch', performedAction: 'Engaged park brake, left ignition on', result: 'fail', scoreDelta: -10, timestamp: '00:25' },
      { stepIndex: 2, stepName: 'Wind Direction Assessment', expectedAction: 'Stand upwind of smoke plume before opening hood', performedAction: 'Stood downwind (smoke inhalation hazard)', result: 'critical_error', scoreDelta: -20, timestamp: '01:15' },
      { stepIndex: 3, stepName: 'Extinguisher Operation (PASS)', expectedAction: 'Pull safety pin, Aim nozzle at base, Squeeze, Sweep', performedAction: 'Attempted to squeeze trigger without removing pin', result: 'critical_error', scoreDelta: -25, timestamp: '02:30' },
      { stepIndex: 4, stepName: 'Secondary Foam Application', expectedAction: 'Apply AFFF foam once pin removed', performedAction: 'Applied foam to base of fire', result: 'pass', scoreDelta: 15, timestamp: '04:10' },
    ]
  },
  {
    id: 'ast-9005',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-RC-3088',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety',
    scenarioName: 'Transformer Substation Electrical Flashover CO2 Extinction',
    score: 85,
    correctActions: 7,
    wrongActions: 1,
    criticalErrors: 0,
    passFail: 'Pass',
    duration: '04m 05s',
    dateTime: '2026-09-10 10:15:00',
    stepDetails: [
      { stepIndex: 1, stepName: 'High Voltage Isolation', expectedAction: 'Trip Main Circuit Breaker V-102', performedAction: 'Tripped V-102 breaker', result: 'pass', scoreDelta: 30, timestamp: '00:35' },
      { stepIndex: 2, stepName: 'CO2 Extinguisher Selection', expectedAction: 'Select 10kg Carbon Dioxide Extinguisher', performedAction: 'Selected CO2 extinguisher', result: 'pass', scoreDelta: 20, timestamp: '01:20' },
      { stepIndex: 3, stepName: 'Discharge Hose Handling', expectedAction: 'Hold insulated horn handle (avoid frostbite)', performedAction: 'Slight slip on horn grip, corrected position', result: 'fail', scoreDelta: -5, timestamp: '02:10' },
      { stepIndex: 4, stepName: 'Evacuation Clearance', expectedAction: 'Clear area of non-essential personnel', performedAction: 'Cleared 15m radius area', result: 'pass', scoreDelta: 35, timestamp: '03:45' },
    ]
  },
  {
    id: 'ast-9006',
    workerId: 'w-105',
    workerName: 'Pankaj Kumar Saw',
    employeeId: 'JHK-RM-9102',
    moduleId: 'm-gas',
    moduleName: 'Gas Safety',
    scenarioName: 'Sulfur Dioxide (SO2) Scrubber Emergency Shutdown',
    score: 88,
    correctActions: 7,
    wrongActions: 1,
    criticalErrors: 0,
    passFail: 'Pass',
    duration: '04m 45s',
    dateTime: '2026-09-05 15:20:18',
    stepDetails: [
      { stepIndex: 1, stepName: 'Full PPE Inspection', expectedAction: 'Inspect Neoprene Suit & Chem-Resistant Gloves', performedAction: 'Inspected PPE for micro-tears', result: 'pass', scoreDelta: 20, timestamp: '00:40' },
      { stepIndex: 2, stepName: 'Acid Pump Bypass', expectedAction: 'Switch Pump P-304 to recirculating bypass', performedAction: 'Switched P-304 to bypass mode', result: 'pass', scoreDelta: 25, timestamp: '01:50' },
      { stepIndex: 3, stepName: 'Neutralization Agent Dosing', expectedAction: 'Inject Lime Slurry at 120 L/min', performedAction: 'Injected at 110 L/min (slight rate delay)', result: 'fail', scoreDelta: -7, timestamp: '03:10' },
      { stepIndex: 4, stepName: 'Final Atmospheric Verification', expectedAction: 'Test ambient air for SO2 < 2 ppm', performedAction: 'Sensor confirmed 0.4 ppm SO2', result: 'pass', scoreDelta: 30, timestamp: '04:30' },
    ]
  }
];
