import type { Certificate } from '../types';

/**
 * DEMO / MOCK certificate registry.
 * These are simulated records used for UI preview only — no actual
 * government-issued certificates, seals, or cryptographic signatures.
 */
export const mockCertificates: Certificate[] = [
  {
    id: 'cert-01',
    certificateId: 'JH-SAF-2026-88421',
    workerId: 'w-101',
    workerName: 'Rajesh Kumar Mahato',
    employeeId: 'JHK-BS-8842',
    sector: 'Bokaro Steel Plant',
    moduleId: 'm-gas',
    moduleName: 'Gas Safety (Blast Furnace Isolation)',
    resultGrade: 'Grade A (94%)',
    issueDate: '2026-09-08',
    expiryDate: '2027-09-08',
    status: 'Active',
    verificationCode: 'DEMO-8F4B-109E-237A',
    issuerDepartment: 'SurakshaAR Training Registry (Simulated)',
  },
  {
    id: 'cert-02',
    certificateId: 'JH-SAF-2026-62112',
    workerId: 'w-103',
    workerName: 'Sunita Hembrom',
    employeeId: 'JHK-JM-6211',
    sector: 'Jamshedpur Metallurgy',
    moduleId: 'm-mach',
    moduleName: 'Machinery Safety (Overhead Crane Interlock)',
    resultGrade: 'Grade A+ (100%)',
    issueDate: '2026-08-25',
    expiryDate: '2027-08-25',
    status: 'Active',
    verificationCode: 'DEMO-7C9E-011B-9482',
    issuerDepartment: 'SurakshaAR Training Registry (Simulated)',
  },
  {
    id: 'cert-03',
    certificateId: 'JH-SAF-2025-91023',
    workerId: 'w-105',
    workerName: 'Pankaj Kumar Saw',
    employeeId: 'JHK-RM-9102',
    sector: 'Ramgarh Chemical Works',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety (Chemical Foam Response)',
    resultGrade: 'Grade B+ (88%)',
    issueDate: '2025-09-10',
    expiryDate: '2026-09-10',
    status: 'Expired',
    verificationCode: 'DEMO-3A11-B980-249C',
    issuerDepartment: 'SurakshaAR Training Registry (Simulated)',
  },
  {
    id: 'cert-04',
    certificateId: 'JH-SAF-2026-77014',
    workerId: 'w-108',
    workerName: 'Anjali Tirkey',
    employeeId: 'JHK-JM-7701',
    sector: 'Jamshedpur Metallurgy',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety (Electrical Substation)',
    resultGrade: 'Grade A (96%)',
    issueDate: '2026-09-04',
    expiryDate: '2027-09-04',
    status: 'Active',
    verificationCode: 'DEMO-1D09-E884-12A8',
    issuerDepartment: 'SurakshaAR Training Registry (Simulated)',
  },
  {
    id: 'cert-05',
    certificateId: 'JH-SAF-2026-30885',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-RC-3088',
    sector: 'Ranchi Heavy Electricals',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety (CO2 Substation Extinction)',
    resultGrade: 'Grade B (85%)',
    issueDate: '2026-09-10',
    expiryDate: '2027-09-10',
    status: 'Pending',
    verificationCode: 'DEMO-9E41-0283-7102',
    issuerDepartment: 'SurakshaAR Training Registry (Simulated)',
  },
  {
    id: 'cert-06',
    certificateId: 'JH-SAF-2025-44193',
    workerId: 'w-102',
    workerName: 'Amit Singh Munda',
    employeeId: 'JHK-DC-4190',
    sector: 'Dhanbad Coal Fields',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety (Belt Conveyor Fire)',
    resultGrade: 'Grade B (88%)',
    issueDate: '2025-10-02',
    expiryDate: '2026-10-02',
    status: 'Expiring Soon',
    verificationCode: 'DEMO-2C15-A884-3340',
    issuerDepartment: 'SurakshaAR Training Registry (Simulated)',
  },
  {
    id: 'cert-07',
    certificateId: 'JH-SAF-2025-90127',
    workerId: 'w-106',
    workerName: 'Deepak Prasad Soren',
    employeeId: 'JHK-BS-9012',
    sector: 'Bokaro Steel Plant',
    moduleId: 'm-gas',
    moduleName: 'Gas Safety (CO Monitor Response)',
    resultGrade: 'Grade A (90%)',
    issueDate: '2025-09-30',
    expiryDate: '2026-09-30',
    status: 'Expiring Soon',
    verificationCode: 'DEMO-6E82-1904-5521',
    issuerDepartment: 'SurakshaAR Training Registry (Simulated)',
  },
];
