import type { Certificate } from '../types';

export const mockCertificates: Certificate[] = [
  {
    id: 'cert-01',
    certificateId: 'JH-SAF-2026-88421',
    workerId: 'w-101',
    workerName: 'Rajesh Kumar Mahato',
    employeeId: 'JHK-CZ-8842',
    sector: 'Dhanbad Region-1',
    moduleId: 'm-gas',
    moduleName: 'Gas Leak & Confined Space',
    resultGrade: 'Passed (94%)',
    issueDate: '2026-09-08',
    expiryDate: '2027-09-08',
    status: 'Active',
    verificationCode: 'DEMO-8F4B-109E-237A',
    issuerDepartment: 'SURAKSHAAR Training & Compliance Registry',
  },
  {
    id: 'cert-02',
    certificateId: 'JH-SAF-2026-62112',
    workerId: 'w-103',
    workerName: 'Sunita Hembrom',
    employeeId: 'JHK-SE-6211',
    sector: 'Ranchi Region',
    moduleId: 'm-mach',
    moduleName: 'Machinery',
    resultGrade: 'Passed (98%)',
    issueDate: '2026-08-25',
    expiryDate: '2027-08-25',
    status: 'Active',
    verificationCode: 'DEMO-7C9E-011B-9482',
    issuerDepartment: 'SURAKSHAAR Training & Compliance Registry',
  },
  {
    id: 'cert-03',
    certificateId: 'JH-SAF-2025-91023',
    workerId: 'w-105',
    workerName: 'Pankaj Kumar Saw',
    employeeId: 'JHK-SE-9102',
    sector: 'Chaibasa Region',
    moduleId: 'm-fire',
    moduleName: 'Fire & Explosion Response',
    resultGrade: 'Passed (88%)',
    issueDate: '2025-09-10',
    expiryDate: '2026-09-10',
    status: 'Expired',
    verificationCode: 'DEMO-3A11-B980-249C',
    issuerDepartment: 'SURAKSHAAR Training & Compliance Registry',
  },
  {
    id: 'cert-04',
    certificateId: 'JH-SAF-2026-77014',
    workerId: 'w-108',
    workerName: 'Anjali Tirkey',
    employeeId: 'JHK-SE-7701',
    sector: 'Bhubaneswar Region-1',
    moduleId: 'm-fire',
    moduleName: 'Fire & Explosion Response',
    resultGrade: 'Passed (96%)',
    issueDate: '2026-09-04',
    expiryDate: '2027-09-04',
    status: 'Active',
    verificationCode: 'DEMO-1D09-E884-12A8',
    issuerDepartment: 'SURAKSHAAR Training & Compliance Registry',
  },
  {
    id: 'cert-05',
    certificateId: 'JH-SAF-2026-30885',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-SE-3088',
    sector: 'Ranchi Region',
    moduleId: 'm-fire',
    moduleName: 'Fire & Explosion Response',
    resultGrade: 'Passed (88%)',
    issueDate: '2026-09-10',
    expiryDate: '2027-09-10',
    status: 'Active',
    verificationCode: 'DEMO-9E41-0283-7102',
    issuerDepartment: 'SURAKSHAAR Training & Compliance Registry',
  },
  {
    id: 'cert-06',
    certificateId: 'JH-SAF-2025-44193',
    workerId: 'w-102',
    workerName: 'Amit Singh Munda',
    employeeId: 'JHK-CZ-4190',
    sector: 'Dhanbad Region-1',
    moduleId: 'm-fire',
    moduleName: 'Fire & Explosion Response',
    resultGrade: 'Passed (88%)',
    issueDate: '2025-10-02',
    expiryDate: '2026-10-02',
    status: 'Expiring Soon',
    verificationCode: 'DEMO-2C15-A884-3340',
    issuerDepartment: 'SURAKSHAAR Training & Compliance Registry',
  },
  {
    id: 'cert-07',
    certificateId: 'JH-SAF-2025-90127',
    workerId: 'w-106',
    workerName: 'Deepak Prasad Soren',
    employeeId: 'JHK-CZ-9012',
    sector: 'Koderma Region',
    moduleId: 'm-gas',
    moduleName: 'Gas Leak & Confined Space',
    resultGrade: 'Passed (91%)',
    issueDate: '2025-09-30',
    expiryDate: '2026-09-30',
    status: 'Expiring Soon',
    verificationCode: 'DEMO-6E82-1904-5521',
    issuerDepartment: 'SURAKSHAAR Training & Compliance Registry',
  }
];
