import type { RetentionRecord } from '../types';

export const mockRetentionRecords: RetentionRecord[] = [
  {
    id: 'ret-01',
    workerId: 'w-101',
    workerName: 'Rajesh Kumar Mahato',
    employeeId: 'JHK-BS-8842',
    sector: 'Bokaro Steel Plant',
    moduleName: 'Gas Safety (Blast Furnace Isolation)',
    lastTrainingDate: '2026-08-12',
    day1Status: 'Completed',
    day1Score: 98,
    day7Status: 'Completed',
    day7Score: 94,
    day30Status: 'Completed',
    day30Score: 92,
    auditCleared: true,
  },
  {
    id: 'ret-02',
    workerId: 'w-102',
    workerName: 'Amit Singh Munda',
    employeeId: 'JHK-DC-4190',
    sector: 'Dhanbad Coal Fields',
    moduleName: 'Gas Safety (Methane Calibration)',
    lastTrainingDate: '2026-09-11',
    day1Status: 'Completed',
    day1Score: 84,
    day7Status: 'Scheduled',
    day7Score: undefined,
    day30Status: 'Pending',
    day30Score: undefined,
    auditCleared: false,
  },
  {
    id: 'ret-03',
    workerId: 'w-103',
    workerName: 'Sunita Hembrom',
    employeeId: 'JHK-JM-6211',
    sector: 'Jamshedpur Metallurgy',
    moduleName: 'Machinery Safety (Crane Interlock)',
    lastTrainingDate: '2026-08-25',
    day1Status: 'Completed',
    day1Score: 100,
    day7Status: 'Completed',
    day7Score: 98,
    day30Status: 'Completed',
    day30Score: 96,
    auditCleared: true,
  },
  {
    id: 'ret-04',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-RC-3088',
    sector: 'Ranchi Heavy Electricals',
    moduleName: 'Fire Safety (CO2 Extinction)',
    lastTrainingDate: '2026-09-10',
    day1Status: 'Completed',
    day1Score: 88,
    day7Status: 'Scheduled',
    day7Score: undefined,
    day30Status: 'Pending',
    day30Score: undefined,
    auditCleared: false,
  },
  {
    id: 'ret-05',
    workerId: 'w-105',
    workerName: 'Pankaj Kumar Saw',
    employeeId: 'JHK-RM-9102',
    sector: 'Ramgarh Chemical Works',
    moduleName: 'Gas Safety (SO2 Scrubber)',
    lastTrainingDate: '2026-09-05',
    day1Status: 'Completed',
    day1Score: 92,
    day7Status: 'Completed',
    day7Score: 88,
    day30Status: 'Scheduled',
    day30Score: undefined,
    auditCleared: false,
  }
];

export const mockRetentionCurveData = [
  { day: 'Day 0 (Immediate)', expectedRetention: 100, actualRetention: 98.4 },
  { day: 'Day 1 Post-Audit', expectedRetention: 92, actualRetention: 96.2 },
  { day: 'Day 7 Field Audit', expectedRetention: 82, actualRetention: 88.4 },
  { day: 'Day 14 Practice Shift', expectedRetention: 75, actualRetention: 84.1 },
  { day: 'Day 30 Compliance Check', expectedRetention: 70, actualRetention: 82.1 },
];
