import type { RetrainingRecord } from '../types';

export const mockRetrainingRecords: RetrainingRecord[] = [
  {
    id: 'ret-301',
    workerId: 'w-102',
    workerName: 'Amit Singh Munda',
    employeeId: 'JHK-DC-4190',
    sector: 'Dhanbad Coal Fields',
    moduleId: 'm-gas',
    moduleName: 'Gas Safety',
    weakArea: 'SCBA Cylinder Pressure Zeroing & Methane Calibration',
    recommendation: 'Complete SCBA 3D Refresher Module & Calibration Bench Trial',
    status: 'Assigned',
    assignedDate: '2026-09-12',
    initialScore: 68,
  },
  {
    id: 'ret-302',
    workerId: 'w-107',
    workerName: 'Manoj Kumar Gupta',
    employeeId: 'JHK-DC-5534',
    sector: 'Dhanbad Coal Fields',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety',
    weakArea: 'Extinguisher Pin Pull Sequence & Downwind Positioning',
    recommendation: 'Mandatory Class B Extinguisher Practical Drill & Wind Drift Sim',
    status: 'Reassessment Pending',
    assignedDate: '2026-09-13',
    initialScore: 54,
  },
  {
    id: 'ret-303',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-RC-3088',
    sector: 'Ranchi Heavy Electricals',
    moduleId: 'm-mach',
    moduleName: 'Machinery Safety',
    weakArea: 'Electrical Isolation Lock Sequence (LOTO)',
    recommendation: 'LOTO Protocol Verification Drill (Level 2)',
    status: 'Completed',
    assignedDate: '2026-08-20',
    reassessmentDate: '2026-09-01',
    initialScore: 72,
    reassessmentScore: 92,
    scoreImprovement: 20,
  },
  {
    id: 'ret-304',
    workerId: 'w-105',
    workerName: 'Pankaj Kumar Saw',
    employeeId: 'JHK-RM-9102',
    sector: 'Ramgarh Chemical Works',
    moduleId: 'm-gas',
    moduleName: 'Gas Safety',
    weakArea: 'SO2 Scrubber Neutralization Dosing Speed',
    recommendation: 'Chemical Acid Scrubber Rapid Response Retraining',
    status: 'In Progress',
    assignedDate: '2026-09-06',
    initialScore: 76,
  },
  {
    id: 'ret-305',
    workerId: 'w-106',
    workerName: 'Deepak Prasad Soren',
    employeeId: 'JHK-BS-9012',
    sector: 'Bokaro Steel Plant',
    moduleId: 'm-mach',
    moduleName: 'Machinery Safety',
    weakArea: 'Billet Guard Interlock Bypass Hazard',
    recommendation: 'Interlock Bypass Protocol Re-evaluation',
    status: 'Recommended',
    assignedDate: '2026-09-13',
    initialScore: 64,
  },
  {
    id: 'ret-306',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-RC-3088',
    sector: 'Ranchi Heavy Electricals',
    moduleId: 'm-fire',
    moduleName: 'Fire Safety',
    weakArea: 'CO2 Horn-Handle Frostbite Risk During Discharge',
    recommendation: 'CO2 Extinguisher Handling Micro-Drill (Level 1)',
    status: 'In Progress',
    assignedDate: '2026-09-09',
    initialScore: 85,
  },
  {
    id: 'ret-307',
    workerId: 'w-103',
    workerName: 'Sunita Hembrom',
    employeeId: 'JHK-JM-6211',
    sector: 'Jamshedpur Metallurgy',
    moduleId: 'm-mach',
    moduleName: 'Machinery Safety',
    weakArea: 'Hook Latch Inspection Before Load Lifting',
    recommendation: 'Rigging & Hook Latch Verification Refresher',
    status: 'Completed',
    assignedDate: '2026-08-10',
    reassessmentDate: '2026-08-28',
    initialScore: 81,
    reassessmentScore: 96,
    scoreImprovement: 15,
  },
];
