import type { RetrainingRecord } from '../types';

export const mockRetrainingRecords: RetrainingRecord[] = [
  {
    id: 'ret-301',
    workerId: 'w-102',
    workerName: 'Amit Singh Munda',
    employeeId: 'JHK-CZ-4190',
    sector: 'Dhanbad Region-1',
    moduleId: 'm-gas',
    moduleName: 'Gas Leak & Confined Space',
    weakArea: 'PPE Selection in Hazard Zone',
    recommendation: 'Targeted PPE Selection Training → PPE Practice → Reassessment',
    status: 'Assigned',
    assignedDate: '2026-09-12',
    initialScore: 92, // Failed due to Critical Error (bypassed PPE)
  },
  {
    id: 'ret-302',
    workerId: 'w-107',
    workerName: 'Manoj Kumar Gupta',
    employeeId: 'JHK-CZ-5534',
    sector: 'Dhanbad Region-2',
    moduleId: 'm-fire',
    moduleName: 'Fire & Explosion Response',
    weakArea: 'Extinguisher Selection & Evacuation Sequence',
    recommendation: 'Targeted Extinguisher Training → Extinguisher Practice → Reassessment',
    status: 'Reassessment Pending',
    assignedDate: '2026-09-13',
    initialScore: 54,
  },
  {
    id: 'ret-303',
    workerId: 'w-104',
    workerName: 'Vikramaditya Oraon',
    employeeId: 'JHK-SE-3088',
    sector: 'Ranchi Region',
    moduleId: 'm-mach',
    moduleName: 'Machinery',
    weakArea: 'Interactions & Guard Safety',
    recommendation: 'Targeted Guard Safety Training → Practice → Reassessment',
    status: 'Completed',
    assignedDate: '2026-08-20',
    reassessmentDate: '2026-09-01',
    initialScore: 72,
    reassessmentScore: 92,
    scoreImprovement: 20,
  },
  {
    id: 'ret-304',
    workerId: 'w-105',
    workerName: 'Pankaj Kumar Saw',
    employeeId: 'JHK-SE-9102',
    sector: 'Chaibasa Region',
    moduleId: 'm-gas',
    moduleName: 'Gas Leak & Confined Space',
    weakArea: 'Hazard Zone Recognition',
    recommendation: 'Targeted Hazard Zone Training → Practice → Reassessment',
    status: 'In Progress',
    assignedDate: '2026-09-06',
    initialScore: 76,
  },
  {
    id: 'ret-305',
    workerId: 'w-106',
    workerName: 'Deepak Prasad Soren',
    employeeId: 'JHK-CZ-9012',
    sector: 'Koderma Region',
    moduleId: 'm-mach',
    moduleName: 'Machinery',
    weakArea: 'Hazard Detection & Emergency Response',
    recommendation: 'Targeted Emergency Response Training → Practice → Reassessment',
    status: 'Recommended',
    assignedDate: '2026-09-13',
    initialScore: 64,
  }
];
