import type { Worker } from '../types';

export const mockWorkers: Worker[] = [
  {
    id: 'w-101',
    employeeId: 'JHK-BS-8842',
    name: 'Rajesh Kumar Mahato',
    sector: 'Bokaro Steel Plant',
    plant: 'Blast Furnace Shop #2',
    role: 'Senior Furnace Operator',
    email: 'rajesh.mahato@bokarosteel.jh.gov.in',
    phone: '+91 94311 20491',
    joinedDate: '2019-04-15',
    safetyOfficer: 'Inspector V.K. Sharma',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 94,
    overallCompetency: 'Strong',
    lastAssessmentDate: '2026-09-08',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 3: Advanced Suppression', status: 'Completed', completionPercentage: 100, score: 96, lastUpdated: '2026-08-12' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 3: Emergency Leak Isolation', status: 'Completed', completionPercentage: 100, score: 92, lastUpdated: '2026-09-08' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 3: LOTO Protocol', status: 'Completed', completionPercentage: 100, score: 94, lastUpdated: '2026-07-20' },
    ],
    weakAreas: ['Gas Detector Sensor Zeroing'],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  },
  {
    id: 'w-102',
    employeeId: 'JHK-DC-4190',
    name: 'Amit Singh Munda',
    sector: 'Dhanbad Coal Fields',
    plant: 'Jharia Shaft No. 4 Underground',
    role: 'Underground Mine Safety Marshal',
    email: 'amit.munda@bccl.jh.gov.in',
    phone: '+91 98352 11092',
    joinedDate: '2021-02-10',
    safetyOfficer: 'Divisional Officer S.N. Roy',
    overallStatus: 'Retraining Required',
    modulesCompleted: 2,
    latestScore: 68,
    overallCompetency: 'Needs Retraining',
    lastAssessmentDate: '2026-09-11',
    certificatesCount: 1,
    retrainingStatus: 'Assigned',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 3: Belt Conveyor Fire', status: 'Completed', completionPercentage: 100, score: 88, lastUpdated: '2026-06-14' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 2: Methane Sensor Calibration', status: 'Retraining', completionPercentage: 65, score: 68, lastUpdated: '2026-09-11' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 1: Haulage Winch Operation', status: 'In Progress', completionPercentage: 40, score: 72, lastUpdated: '2026-08-01' },
    ],
    weakAreas: ['SCBA Mask Pressure Verification', 'Methane Leak Escalation Protocol'],
    retentionDay1: 'Completed',
    retentionDay7: 'Scheduled',
    retentionDay30: 'Pending',
  },
  {
    id: 'w-103',
    employeeId: 'JHK-JM-6211',
    name: 'Sunita Hembrom',
    sector: 'Jamshedpur Metallurgy',
    plant: 'Rolling Mill Division B',
    role: 'Crane & Rigging Specialist',
    email: 'sunita.hembrom@tatasteel.jh.gov.in',
    phone: '+91 97710 44321',
    joinedDate: '2020-09-01',
    safetyOfficer: 'Chief Inspector P. Kujur',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 98,
    overallCompetency: 'Strong',
    lastAssessmentDate: '2026-09-02',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 3: Electrical Panel Flash', status: 'Completed', completionPercentage: 100, score: 98, lastUpdated: '2026-05-19' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 3: Toxic Fume Extraction', status: 'Completed', completionPercentage: 100, score: 96, lastUpdated: '2026-09-02' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 3: Overhead Crane Interlock', status: 'Completed', completionPercentage: 100, score: 100, lastUpdated: '2026-08-25' },
    ],
    weakAreas: [],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  },
  {
    id: 'w-104',
    employeeId: 'JHK-RC-3088',
    name: 'Vikramaditya Oraon',
    sector: 'Ranchi Heavy Electricals',
    plant: 'High Voltage Transformer Shop',
    role: 'Electrical Maintenance Technician',
    email: 'vikram.oraon@hec.jh.gov.in',
    phone: '+91 91223 88104',
    joinedDate: '2022-11-18',
    safetyOfficer: 'Inspector V.K. Sharma',
    overallStatus: 'In Training',
    modulesCompleted: 1,
    latestScore: 82,
    overallCompetency: 'Developing',
    lastAssessmentDate: '2026-09-10',
    certificatesCount: 1,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 2: CO2 Extinguisher Deployment', status: 'Completed', completionPercentage: 100, score: 85, lastUpdated: '2026-09-10' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 1: Basic Cylinder Storage', status: 'In Progress', completionPercentage: 50, score: 78, lastUpdated: '2026-08-30' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 1: Press Interlock Verification', status: 'Not Started', completionPercentage: 0, score: 0, lastUpdated: '2026-08-01' },
    ],
    weakAreas: ['Electrical Isolation Lock Sequence'],
    retentionDay1: 'Completed',
    retentionDay7: 'Scheduled',
    retentionDay30: 'Pending',
  },
  {
    id: 'w-105',
    employeeId: 'JHK-RM-9102',
    name: 'Pankaj Kumar Saw',
    sector: 'Ramgarh Chemical Works',
    plant: 'Sulfuric Acid Recovery Unit',
    role: 'Process Plant Technician',
    email: 'pankaj.saw@rcw.jh.gov.in',
    phone: '+91 93041 55290',
    joinedDate: '2018-01-22',
    safetyOfficer: 'Divisional Officer S.N. Roy',
    overallStatus: 'Passed',
    modulesCompleted: 2,
    latestScore: 89,
    overallCompetency: 'Developing',
    lastAssessmentDate: '2026-09-05',
    certificatesCount: 2,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 3: Chemical Foam Fire', status: 'Completed', completionPercentage: 100, score: 90, lastUpdated: '2026-07-11' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 3: SO2 Scrubbing Response', status: 'Completed', completionPercentage: 100, score: 88, lastUpdated: '2026-09-05' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 2: Pump Valve Safety', status: 'In Progress', completionPercentage: 70, score: 84, lastUpdated: '2026-08-20' },
    ],
    weakAreas: ['Acid Splash Guard Attachment'],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Scheduled',
  },
  {
    id: 'w-106',
    employeeId: 'JHK-BS-9012',
    name: 'Deepak Prasad Soren',
    sector: 'Bokaro Steel Plant',
    plant: 'Coke Oven Battery #4',
    role: 'Coke Discharge Controller',
    email: 'deepak.soren@bokarosteel.jh.gov.in',
    phone: '+91 94701 92831',
    joinedDate: '2021-07-14',
    safetyOfficer: 'Inspector V.K. Sharma',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 91,
    overallCompetency: 'Strong',
    lastAssessmentDate: '2026-09-01',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 3: Coke Dust Suppression', status: 'Completed', completionPercentage: 100, score: 94, lastUpdated: '2026-08-05' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 3: CO Monitor Response', status: 'Completed', completionPercentage: 100, score: 90, lastUpdated: '2026-09-01' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 3: Pusher Car Interlock', status: 'Completed', completionPercentage: 100, score: 89, lastUpdated: '2026-06-28' },
    ],
    weakAreas: [],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  },
  {
    id: 'w-107',
    employeeId: 'JHK-DC-5534',
    name: 'Manoj Kumar Gupta',
    sector: 'Dhanbad Coal Fields',
    plant: 'Sijua Opencast Project',
    role: 'Heavy Earth Mover Operator',
    email: 'manoj.gupta@bccl.jh.gov.in',
    phone: '+91 98012 33499',
    joinedDate: '2017-03-30',
    safetyOfficer: 'Divisional Officer S.N. Roy',
    overallStatus: 'Failed',
    modulesCompleted: 1,
    latestScore: 54,
    overallCompetency: 'Needs Retraining',
    lastAssessmentDate: '2026-09-13',
    certificatesCount: 0,
    retrainingStatus: 'Reassessment Pending',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 1: Dumper Engine Fire', status: 'Retraining', completionPercentage: 45, score: 54, lastUpdated: '2026-09-13' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 1: Exhaust Fume Inspection', status: 'In Progress', completionPercentage: 30, score: 60, lastUpdated: '2026-08-10' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 1: Blind Spot Clearance', status: 'Not Started', completionPercentage: 0, score: 0, lastUpdated: '2026-07-15' },
    ],
    weakAreas: ['Fire Extinguisher Pin Pull Sequence', 'Emergency Engine Cutoff Switch'],
    retentionDay1: 'Scheduled',
    retentionDay7: 'Pending',
    retentionDay30: 'Pending',
  },
  {
    id: 'w-108',
    employeeId: 'JHK-JM-7701',
    name: 'Anjali Tirkey',
    sector: 'Jamshedpur Metallurgy',
    plant: 'Wire Rod Mill Division',
    role: 'Quality & Safety Inspector',
    email: 'anjali.tirkey@tatasteel.jh.gov.in',
    phone: '+91 97099 11200',
    joinedDate: '2023-01-15',
    safetyOfficer: 'Chief Inspector P. Kujur',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 96,
    overallCompetency: 'Strong',
    lastAssessmentDate: '2026-09-04',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire Safety', stage: 'Stage 3: Electrical Substation', status: 'Completed', completionPercentage: 100, score: 96, lastUpdated: '2026-07-29' },
      { moduleId: 'm-gas', moduleName: 'Gas Safety', stage: 'Stage 3: Argon Shield Gas Purge', status: 'Completed', completionPercentage: 100, score: 95, lastUpdated: '2026-09-04' },
      { moduleId: 'm-mach', moduleName: 'Machinery Safety', stage: 'Stage 3: High-Speed Billet Guard', status: 'Completed', completionPercentage: 100, score: 97, lastUpdated: '2026-08-18' },
    ],
    weakAreas: [],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  }
];
