import type { Worker } from '../types';

export const mockWorkers: Worker[] = [
  {
    id: 'w-101',
    employeeId: 'JHK-CZ-8842',
    name: 'Rajesh Kumar Mahato',
    sector: 'Dhanbad Region-1',
    plant: 'Central Mine Site #2',
    role: 'Safety Marshal',
    email: 'rajesh.mahato@surakshaar.jh.gov.in',
    phone: '+91 94311 20491',
    joinedDate: '2019-04-15',
    safetyOfficer: 'Inspector V.K. Sharma',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 94,
    overallCompetency: 'Competent',
    lastAssessmentDate: '2026-09-08',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Evacuation Sequence', status: 'Completed', completionPercentage: 100, score: 96, lastUpdated: '2026-08-12' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'Confined Space Entry', status: 'Completed', completionPercentage: 100, score: 92, lastUpdated: '2026-09-08' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Hazard Detection', status: 'Completed', completionPercentage: 100, score: 94, lastUpdated: '2026-07-20' },
    ],
    weakAreas: [],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  },
  {
    id: 'w-102',
    employeeId: 'JHK-CZ-4190',
    name: 'Amit Singh Munda',
    sector: 'Dhanbad Region-1',
    plant: 'Jharia Shaft No. 4',
    role: 'Underground Operator',
    email: 'amit.munda@surakshaar.jh.gov.in',
    phone: '+91 98352 11092',
    joinedDate: '2021-02-10',
    safetyOfficer: 'Divisional Officer S.N. Roy',
    overallStatus: 'Needs Retraining',
    modulesCompleted: 2,
    latestScore: 92, // 92% score with 1 critical error = Fail
    overallCompetency: 'Needs Retraining',
    lastAssessmentDate: '2026-09-11',
    certificatesCount: 1,
    retrainingStatus: 'Assigned',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Use Extinguisher', status: 'Completed', completionPercentage: 100, score: 88, lastUpdated: '2026-06-14' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'PPE Selection', status: 'Retraining', completionPercentage: 65, score: 92, lastUpdated: '2026-09-11' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Interactions & Guard Safety', status: 'In Progress', completionPercentage: 40, score: 72, lastUpdated: '2026-08-01' },
    ],
    weakAreas: ['PPE Selection in Hazard Zone'],
    retentionDay1: 'Completed',
    retentionDay7: 'Scheduled',
    retentionDay30: 'Pending',
  },
  {
    id: 'w-103',
    employeeId: 'JHK-SE-6211',
    name: 'Sunita Hembrom',
    sector: 'Ranchi Region',
    plant: 'Industrial Unit B',
    role: 'Equipment Specialist',
    email: 'sunita.hembrom@surakshaar.jh.gov.in',
    phone: '+91 97710 44321',
    joinedDate: '2020-09-01',
    safetyOfficer: 'Chief Inspector P. Kujur',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 98,
    overallCompetency: 'Competent',
    lastAssessmentDate: '2026-09-02',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Evacuation Sequence', status: 'Completed', completionPercentage: 100, score: 98, lastUpdated: '2026-05-19' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'Confined Space Entry', status: 'Completed', completionPercentage: 100, score: 96, lastUpdated: '2026-09-02' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Emergency Response', status: 'Completed', completionPercentage: 100, score: 100, lastUpdated: '2026-08-25' },
    ],
    weakAreas: [],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  },
  {
    id: 'w-104',
    employeeId: 'JHK-SE-3088',
    name: 'Vikramaditya Oraon',
    sector: 'Ranchi Region',
    plant: 'Heavy Engineering Shop',
    role: 'Maintenance Technician',
    email: 'vikram.oraon@surakshaar.jh.gov.in',
    phone: '+91 91223 88104',
    joinedDate: '2022-11-18',
    safetyOfficer: 'Inspector V.K. Sharma',
    overallStatus: 'In Training',
    modulesCompleted: 1,
    latestScore: 82,
    overallCompetency: 'Competent',
    lastAssessmentDate: '2026-09-10',
    certificatesCount: 1,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Select Extinguisher', status: 'Completed', completionPercentage: 100, score: 85, lastUpdated: '2026-09-10' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'Hazard Recognition', status: 'In Progress', completionPercentage: 50, score: 78, lastUpdated: '2026-08-30' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Operational Readiness', status: 'Not Started', completionPercentage: 0, score: 0, lastUpdated: '2026-08-01' },
    ],
    weakAreas: ['Interactions & Guard Safety'],
    retentionDay1: 'Completed',
    retentionDay7: 'Scheduled',
    retentionDay30: 'Pending',
  },
  {
    id: 'w-105',
    employeeId: 'JHK-SE-9102',
    name: 'Pankaj Kumar Saw',
    sector: 'Chaibasa Region',
    plant: 'Mining Recovery Unit',
    role: 'Process Plant Operator',
    email: 'pankaj.saw@surakshaar.jh.gov.in',
    phone: '+91 93041 55290',
    joinedDate: '2018-01-22',
    safetyOfficer: 'Divisional Officer S.N. Roy',
    overallStatus: 'Passed',
    modulesCompleted: 2,
    latestScore: 89,
    overallCompetency: 'Competent',
    lastAssessmentDate: '2026-09-05',
    certificatesCount: 2,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Use Extinguisher', status: 'Completed', completionPercentage: 100, score: 90, lastUpdated: '2026-07-11' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'Safe Response', status: 'Completed', completionPercentage: 100, score: 88, lastUpdated: '2026-09-05' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Operational Readiness', status: 'In Progress', completionPercentage: 70, score: 84, lastUpdated: '2026-08-20' },
    ],
    weakAreas: ['Hazard Zone Recognition'],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Scheduled',
  },
  {
    id: 'w-106',
    employeeId: 'JHK-CZ-9012',
    name: 'Deepak Prasad Soren',
    sector: 'Koderma Region',
    plant: 'Koderma Area Unit',
    role: 'Plant Controller',
    email: 'deepak.soren@surakshaar.jh.gov.in',
    phone: '+91 94701 92831',
    joinedDate: '2021-07-14',
    safetyOfficer: 'Inspector V.K. Sharma',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 91,
    overallCompetency: 'Competent',
    lastAssessmentDate: '2026-09-01',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Evacuation Sequence', status: 'Completed', completionPercentage: 100, score: 94, lastUpdated: '2026-08-05' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'Confined Space Entry', status: 'Completed', completionPercentage: 100, score: 90, lastUpdated: '2026-09-01' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Emergency Response', status: 'Completed', completionPercentage: 100, score: 89, lastUpdated: '2026-06-28' },
    ],
    weakAreas: [],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  },
  {
    id: 'w-107',
    employeeId: 'JHK-CZ-5534',
    name: 'Manoj Kumar Gupta',
    sector: 'Dhanbad Region-2',
    plant: 'Sijua Area Project',
    role: 'Heavy Equipment Operator',
    email: 'manoj.gupta@surakshaar.jh.gov.in',
    phone: '+91 98012 33499',
    joinedDate: '2017-03-30',
    safetyOfficer: 'Divisional Officer S.N. Roy',
    overallStatus: 'Failed',
    modulesCompleted: 1,
    latestScore: 54,
    overallCompetency: 'Needs Retraining',
    lastAssessmentDate: '2026-09-13',
    certificatesCount: 0,
    retrainingStatus: 'Reassessment Pending',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Select Extinguisher', status: 'Retraining', completionPercentage: 45, score: 54, lastUpdated: '2026-09-13' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'Hazard Recognition', status: 'In Progress', completionPercentage: 30, score: 60, lastUpdated: '2026-08-10' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Operational Readiness', status: 'Not Started', completionPercentage: 0, score: 0, lastUpdated: '2026-07-15' },
    ],
    weakAreas: ['Extinguisher Selection & Use Sequence', 'Evacuation Sequence & Exit Identification'],
    retentionDay1: 'Scheduled',
    retentionDay7: 'Pending',
    retentionDay30: 'Pending',
  },
  {
    id: 'w-108',
    employeeId: 'JHK-SE-7701',
    name: 'Anjali Tirkey',
    sector: 'Bhubaneswar Region-1',
    plant: 'Safety Inspection Division',
    role: 'Safety Inspector',
    email: 'anjali.tirkey@surakshaar.jh.gov.in',
    phone: '+91 97099 11200',
    joinedDate: '2023-01-15',
    safetyOfficer: 'Chief Inspector P. Kujur',
    overallStatus: 'Certified',
    modulesCompleted: 3,
    latestScore: 96,
    overallCompetency: 'Competent',
    lastAssessmentDate: '2026-09-04',
    certificatesCount: 3,
    retrainingStatus: 'Completed',
    moduleProgressList: [
      { moduleId: 'm-fire', moduleName: 'Fire & Explosion Response', stage: 'Evacuation Sequence', status: 'Completed', completionPercentage: 100, score: 96, lastUpdated: '2026-07-29' },
      { moduleId: 'm-gas', moduleName: 'Gas Leak & Confined Space', stage: 'Confined Space Entry', status: 'Completed', completionPercentage: 100, score: 95, lastUpdated: '2026-09-04' },
      { moduleId: 'm-mach', moduleName: 'Machinery', stage: 'Emergency Response', status: 'Completed', completionPercentage: 100, score: 97, lastUpdated: '2026-08-18' },
    ],
    weakAreas: [],
    retentionDay1: 'Completed',
    retentionDay7: 'Completed',
    retentionDay30: 'Completed',
  }
];
